[tool.poetry]
name = "CLCTool"
version = "1.6.2"
description = "CLCTool"

authors = ["SpoinkOSDevs"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
