name: Autotag and Release
on:
  push:
    branches:   
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: create-release
        if: github.event.ref_type == 'tag'
        uses: arco-design/auto-arco-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          changelogPaths: 'docs/changelog.en-US.md,docs/changelog.zh-CN.md'
          tagName: ${{ steps.get_version.outputs.VERSION }}
